apiVersion: v1
version: 3.1.6
appVersion: 2020.3.25
description: MinIO is an object storage server, compatible with Amazon S3 cloud storage service, mainly used for storing unstructured data (such as photos, videos, log files, etc.)
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
name: minio
home: https://min.io
icon: https://codedx.com/wp-content/uploads/2017/03/CodeDx-logo.png 
sources:
- https://github.com/codedx/charts 
maintainers:
- name: CodeDx
  email: support@codedx.com 
engine: gotpl
